ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS packing_photo_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS delivery_photo_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS picked_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP NULL;
