-- Convert validated AI action snapshot to JSONB for querying/debugging.
-- Existing text values are expected to be JSON strings generated by the backend.

ALTER TABLE chat_messages
    ALTER COLUMN validated_action_snapshot DROP DEFAULT,
    ALTER COLUMN validated_action_snapshot TYPE JSONB
        USING CASE
            WHEN validated_action_snapshot IS NULL THEN NULL
            WHEN btrim(validated_action_snapshot::text) = '' THEN NULL
            ELSE validated_action_snapshot::jsonb
        END;

